### ISSUE TITLE
Add connect-timeout for curl

### ISSUE THREAD

**Issue by ghost** [bashup/gitea-cli#2]
When configuring a bad URL (server does not exist), ``gitea-cli`` hangs indefinitely. Please add 

    --connect-timeout 2

to the `curl` call.

**Comment by pjeby** [comment]
I don't quite see the point of adding this to the code, especially not with a not-configurable value for the timeout, but if you want it in your own version, just add the following to your user or site-level config file:

```shell
read-curl() { REPLY=$(curl --connect-timeout 2 "$@"); }
```

I could see adding it as a `GITEA_CONNECT_TIMEOUT` variable or some such, I suppose.

**Comment by ghost** [comment]
`2` was just an example. Any other value would be fine, a configurable value perfect. Incentive: An indefinitely blocking command line tool (just due to bad configuration) which does not provide any output, does not seem right to me.

**Comment by ghost** [comment]
Awesome! Now I understand, "user or size-level config" is of course `.gitearc`. Adding the line given above works great. Thanks! No command line parameter needed.
