### ISSUE TITLE
GITEA_CREATE is mandatory

### ISSUE THREAD

**Issue by ghost** [bashup/gitea-cli#4]
Hello again and sorry to bother you again!

 With that latest version of `gitea-cli` I am getting for `gitea new user/repo`

    ./gitea: line 193: GITEA_CREATE[@]: unbound variable

Only when I add to my `.gitearc`

    GITEA_CREATE=("private=" "true")

the new repository is created.

**Comment by pjeby** [comment]
Sorry about that; the bug slipped past me because I'm using bash 4.4, which doesn't have that problem with array variables.
