### ISSUE TITLE
more user-friendly help

### ISSUE THREAD

**Issue by biocyberman** [bashup/gitea-cli#5]
I was expecting `gitea` bare command or `gitea -h` would print something to remind me about available commands including custom commands.

**Comment by pjeby** [comment]
Well, you could implement -h like so:

```shell
gitea.-h() {
    echo "Options and Commands:"
    read -rd '' -a REPLY < <(compgen -A function gitea.) || true
    printf '\t%s\n' "${REPLY[@]#gitea.}"
}
```

And if you want it to execute on an empty command line or unrecognized command/option, add:

```shell
loco_usage() { gitea -h; _loco_usage; }
```

This will list the commands to stdout then exit with an error and usage message.

I suppose I might implement something like this in a future version, but more likely it would be done upstream in [bashup/loco](https://github.com/bashup/loco).
