### ISSUE TITLE
quickly print full link to repo?

### ISSUE THREAD

**Issue by biocyberman** [bashup/gitea-cli#6]
I am thinking to implement `gitea.info` to do this:

`gitea info myuser/myrepo`

This would print: 
```
https url: https://gitea.example.com/myuser/myrepo.git
SSH url: git@gitea.example.com:myuser/myrepo.git 
(Maybe) Last commit: blah blah commit message #commithashash
```
Can this be done and how?

**Comment by pjeby** [comment]
As of the latest commit, you can do something like:

```shell
gitea.info() {
    gitea exists "$1" && echo "$REPLY" | jq .
}
```

To output a nicely-formatted JSON dump of the repo data.  If you want it in something other than JSON, you can change the `jq .` to something like `jq -r '"https url: \(.html_url)\nSSH url: \(.ssh_url)"'`, expanding upon it to include other data from the JSON as desired.  You'll probably want to read the jq manual for more info if you're going to take that approach.
