### ISSUE TITLE
(No bug) Using this with other Gitea instances

### ISSUE THREAD

**Issue by nerd190** [bashup/gitea-cli#7]
Hi, thanks for this, it seems like what I need! I just cant seem to get it working with another Gitea instance https://git.disroot.org
I was wondering if you would be kind enough to try as I'm sure that its me doing something wrong!
Thank you! 👍

**Comment by pjeby** [comment]
I'm afraid you haven't given me any information to go on here.  Like, what you're trying to do and what isn't working, or how it isn't working, what you expected it to do and what it did instead.  All of that would be kind of a minimum to even figure out what's going on.

**Comment by nerd190** [comment]
I apologise! I thought I had set the instance URL wrong and was enquiring if it was compatable with other instances and perhaps I was missing something! but in fact it was like I said "my fault / no bug", my API key had expired! thank you for the scripts! awesome! 👍
